name: Deploy TEC Platform to Heroku

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Set up Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: Install Python dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Node.js dependencies  
      run: |
        cd frontend
        npm install
    
    - name: Build React app
      run: |
        cd frontend
        npm run build
    
    - name: Test Python backend
      run: |
        cd backend
        python -m pytest --tb=short
      continue-on-error: true
    
    - name: Test React frontend
      run: |
        cd frontend
        npm test -- --coverage --ci --watchAll=false
      continue-on-error: true

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "tecaikids"
        heroku_email: "your-email@example.com"
        buildpack: |
          heroku/nodejs
          heroku/python